-- AlterTable
ALTER TABLE "Photo" ADD COLUMN     "bytes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mime" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "path" TEXT NOT NULL DEFAULT '',
ALTER COLUMN "data" SET DEFAULT '';

